//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APS.ImagenesDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticias
    {
        public int idNoticia { get; set; }
        public byte[] imagen { get; set; }
        public string titular { get; set; }
        public System.DateTime fechaPublicacion { get; set; }
    }
}
