//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APS.ImagenesDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string email { get; set; }
        public string password { get; set; }
        public string DNI { get; set; }
        public string nombreUser { get; set; }
        public string nombreRol { get; set; }
        public Nullable<System.DateTime> fechaNac { get; set; }
        public byte[] imagen { get; set; }
        public string nombre { get; set; }
        public string apellido1 { get; set; }
        public string apellido2 { get; set; }
        public string situacion { get; set; }
    }
}
